export interface Destination {
  id: string;
  name: string;
  nameAr: string;
  img: string;
  tag: string;
  tagAr: string;
  desc: string;
  descAr: string;
  highlights: string[];
  highlightsAr: string[];
}

export const destinations: Destination[] = [
  {
    id: 'cairo',
    name: 'Cairo',
    nameAr: 'القاهرة',
    img: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80&fit=crop',
    tag: 'Capital City',
    tagAr: 'العاصمة',
    desc: "Egypt's sprawling capital is a city of contrasts — ancient mosques tower beside modern skyscrapers. Home to the iconic Khan El-Khalili bazaar and the world-class Grand Egyptian Museum.",
    descAr: 'عاصمة مصر الضخمة مدينة المتناقضات — مساجد عريقة جنباً إلى جنب مع ناطحات السحاب. موطن خان الخليلي الشهير والمتحف المصري الكبير.',
    highlights: ['Khan El-Khalili', 'Islamic Cairo', 'Grand Egyptian Museum', 'Nile Corniche'],
    highlightsAr: ['خان الخليلي', 'القاهرة الإسلامية', 'المتحف المصري الكبير', 'كورنيش النيل'],
  },
  {
    id: 'giza',
    name: 'Giza',
    nameAr: 'الجيزة',
    img: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80&fit=crop',
    tag: 'Ancient Wonder',
    tagAr: 'عجيبة الدنيا',
    desc: 'Home to one of the Seven Wonders of the Ancient World. The Great Pyramids and the enigmatic Sphinx have stood for over 4,500 years.',
    descAr: 'موطن إحدى عجائب الدنيا السبع. الأهرامات العظيمة وأبو الهول الغامض صامدان منذ أكثر من 4500 عام.',
    highlights: ['Great Pyramid of Khufu', 'The Sphinx', 'Solar Boat Museum', 'Sound & Light Show'],
    highlightsAr: ['هرم خوفو الأكبر', 'أبو الهول', 'متحف المركب الشمسية', 'عرض الصوت والضوء'],
  },
  {
    id: 'luxor',
    name: 'Luxor',
    nameAr: 'الأقصر',
    img: 'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?w=800&q=80&fit=crop',
    tag: 'Open-Air Museum',
    tagAr: 'متحف مفتوح',
    desc: "Often called the world's greatest open-air museum. Valley of the Kings, Karnak Temple, and hot air balloon rides over ancient ruins.",
    descAr: 'يُعدّ أعظم متحف مفتوح في العالم. وادي الملوك ومعبد الكرنك ورحلات المنطاد فوق الآثار القديمة.',
    highlights: ['Valley of the Kings', 'Karnak Temple', 'Luxor Temple', 'Hot Air Balloon Ride'],
    highlightsAr: ['وادي الملوك', 'معبد الكرنك', 'معبد الأقصر', 'رحلة بالمنطاد'],
  },
  {
    id: 'aswan',
    name: 'Aswan',
    nameAr: 'أسوان',
    img: 'https://images.unsplash.com/photo-1502013867623-64da150937a4?w=800&q=80&fit=crop',
    tag: 'Nubian Gateway',
    tagAr: 'بوابة النوبة',
    desc: 'A serene retreat on the Nile offering vibrant Nubian culture, the magnificent Abu Simbel temples, and spectacular sunsets.',
    descAr: 'ملاذ هادئ على النيل يوفر ثقافة نوبية نابضة بالحياة ومعابد أبو سمبل الرائعة وغروب شمس خلاب.',
    highlights: ['Abu Simbel', 'Philae Temple', 'Nubian Village', 'Felucca Ride'],
    highlightsAr: ['أبو سمبل', 'معبد فيلة', 'القرية النوبية', 'ركوب الفلوكة'],
  },
  {
    id: 'hurghada',
    name: 'Hurghada',
    nameAr: 'الغردقة',
    img: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&fit=crop',
    tag: 'Red Sea Paradise',
    tagAr: 'جنة البحر الأحمر',
    desc: "Egypt's premier Red Sea resort with crystal-clear waters, world-class diving, and vibrant coral reefs teeming with marine life.",
    descAr: 'المنتجع الأول في البحر الأحمر بمياه صافية وغوص عالمي المستوى وشعاب مرجانية نابضة بالحياة البحرية.',
    highlights: ['Coral Reef Diving', 'Snorkeling Tours', 'Desert Safari', 'Giftun Island'],
    highlightsAr: ['غوص الشعاب المرجانية', 'جولات الغطس', 'سفاري الصحراء', 'جزيرة جفتون'],
  },
  {
    id: 'sharm',
    name: 'Sharm El-Sheikh',
    nameAr: 'شرم الشيخ',
    img: 'https://images.unsplash.com/photo-1548073430-d08e8ac3ae89?w=800&q=80&fit=crop',
    tag: 'Diving Capital',
    tagAr: 'عاصمة الغوص',
    desc: 'World-famous diving destination at the tip of the Sinai Peninsula. Ras Mohammed National Park and Naama Bay offer unparalleled underwater beauty.',
    descAr: 'وجهة غوص مشهورة عالمياً عند طرف شبه جزيرة سيناء. متنظمة رأس محمد وشرم نعمة تقدمان جمالاً تحت الماء لا مثيل له.',
    highlights: ['Ras Mohammed', 'Naama Bay', 'Tiran Island', 'Mount Sinai Hike'],
    highlightsAr: ['رأس محمد', 'خليج نعمة', 'جزيرة تيران', 'تسلق جبل سيناء'],
  },
  {
    id: 'alexandria',
    name: 'Alexandria',
    nameAr: 'الإسكندرية',
    img: 'https://images.unsplash.com/photo-1553956455-54cad90e7a9a?w=800&q=80&fit=crop',
    tag: 'Mediterranean Jewel',
    tagAr: 'جوهرة المتوسط',
    desc: 'The Pearl of the Mediterranean blends Greek, Roman, and Egyptian heritage. The legendary Library of Alexandria and the magnificent Qaitbay Citadel await.',
    descAr: 'لؤلؤة البحر الأبيض تمزج التراث الإغريقي والروماني والمصري. مكتبة الإسكندرية الأسطورية وقلعة قايتباي الرائعة في انتظارك.',
    highlights: ['Library of Alexandria', 'Qaitbay Citadel', 'Catacombs of Kom El Shoqafa', 'Stanley Beach'],
    highlightsAr: ['مكتبة الإسكندرية', 'قلعة قايتباي', 'كاتاكومب كوم الشقافة', 'شاطئ ستانلي'],
  },
  {
    id: 'sinai',
    name: 'Sinai',
    nameAr: 'سيناء',
    img: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&q=80&fit=crop',
    tag: 'Sacred Mountains',
    tagAr: 'الجبال المقدسة',
    desc: 'A land of spiritual significance and breathtaking landscapes. Mount Sinai, St. Catherine\'s Monastery, and the Colored Canyon are unmissable.',
    descAr: 'أرض ذات أهمية روحية ومناظر طبيعية خلابة. جبل سيناء ودير سانت كاترين والوادي الملون لا يمكن تفويتها.',
    highlights: ["Mount Sinai", "St. Catherine's Monastery", "Colored Canyon", "Bedouin Culture"],
    highlightsAr: ['جبل سيناء', 'دير سانت كاترين', 'الوادي الملون', 'الثقافة البدوية'],
  },
  {
    id: 'siwa',
    name: 'Siwa Oasis',
    nameAr: 'واحة سيوة',
    img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&fit=crop',
    tag: 'Desert Oasis',
    tagAr: 'واحة الصحراء',
    desc: 'A remote oasis near the Libyan border with ancient ruins, freshwater springs, and the Oracle Temple where Alexander the Great sought guidance.',
    descAr: 'واحة نائية قرب الحدود الليبية بآثار قديمة وينابيع عذبة ومعبد الأوراكل الذي التمس فيه الإسكندر الأكبر الإرشاد.',
    highlights: ['Oracle Temple', 'Cleopatra Spring', 'Great Sand Sea', 'Shali Fortress'],
    highlightsAr: ['معبد الأوراكل', 'عين كليوباترا', 'بحر الرمال الكبير', 'قلعة شالي'],
  },
  {
    id: 'dahab',
    name: 'Dahab',
    nameAr: 'دهب',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&fit=crop',
    tag: 'Diver\'s Haven',
    tagAr: 'ملاذ الغواصين',
    desc: "A laid-back Bedouin town on the Red Sea coast, famous for the legendary Blue Hole dive site and world-class windsurfing.",
    descAr: 'مدينة بدوية هادئة على ساحل البحر الأحمر، مشهورة بموقع الغوص الأسطوري الثقب الأزرق والتزحلق على الأمواج.',
    highlights: ['Blue Hole Diving', 'Lagoon Windsurfing', 'Bedouin Camps', 'Canyon Snorkeling'],
    highlightsAr: ['غوص الثقب الأزرق', 'ركوب الأمواج في البحيرة', 'مخيمات بدوية', 'غطس الكانيون'],
  },
  {
    id: 'faiyum',
    name: 'Faiyum',
    nameAr: 'الفيوم',
    img: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80&fit=crop',
    tag: 'Scenic Valley',
    tagAr: 'الوادي الخلاب',
    desc: "Egypt's largest oasis offers Wadi El-Rayan waterfalls, Qarun Lake, and a rich tradition of pottery and basket weaving.",
    descAr: 'أكبر واحة في مصر تقدم شلالات وادي الريان وبحيرة قارون وتراثاً غنياً من الفخار وصناعة السلال.',
    highlights: ['Wadi El-Rayan', 'Lake Qarun', 'Pottery Village', 'Whale Valley'],
    highlightsAr: ['وادي الريان', 'بحيرة قارون', 'قرية الفخار', 'وادي الحيتان'],
  },
  {
    id: 'white-desert',
    name: 'White Desert',
    nameAr: 'الصحراء البيضاء',
    img: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80&fit=crop',
    tag: 'Surreal Landscape',
    tagAr: 'مناظر خيالية',
    desc: 'A surreal moonscape of white chalk formations sculpted by wind. Camping under the stars here is one of Egypt\'s most magical experiences.',
    descAr: 'مناظر خيالية من تكوينات الطباشير البيضاء نحتتها الرياح. التخييم تحت النجوم هنا من أكثر التجارب سحراً في مصر.',
    highlights: ['Rock Formations', 'Stargazing Camps', 'Crystal Mountain', 'Black Desert'],
    highlightsAr: ['تكوينات الصخور', 'مخيمات رصد النجوم', 'جبل الكريستال', 'الصحراء السوداء'],
  },
];
